### ISSUE TITLE
Implementing DTX

### ISSUE THREAD

**Issue by botiapa** [DuckerMan/magnum-opus#3]
Could you add support for DTX?

https://opus-codec.org/docs/opus_api-1.3.1/group__opus__encoderctls.html#ga4f053b2db8c5162293213aabfe123773
https://opus-codec.org/docs/opus_api-1.3.1/group__opus__encoderctls.html#gaafbb44454e9f57232b85e4e087337ded

Thank you for maintaining this fork and package!

**Comment by botiapa** [comment]
I added a PR

**Comment by TheRadioGuy** [comment]
Wow, thanks for your contribution!
